CONSUMER_KEY = "HdSR9goDkP1faGusHp9pTVHWk"
CONSUMER_SECRET = "hriwZGgLro5ttfSVi3Tj9UxaSvHDIoBwDDexZ2B43ZXx30UFbu"
ACCESS_TOKEN_KEY = "1369144591434145792-hUpBSf4tthKVhcbD6Kbv9O08rRkVSy"
ACCESS_TOKEN_SECRET = "aOllyCJYxVYO7SsJYxv1LVwOWtm5EZq7qpBVbY91JZsF9"